# Generated by Django 5.2.1 on 2025-05-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('sipnosis', models.TextField(null=True, verbose_name='Imagen')),
                ('genero', models.CharField(max_length=100)),
                ('fecha_estreno', models.DateField()),
                ('opinion', models.TextField(null=True, verbose_name='Opinion')),
            ],
        ),
    ]
