# Generated by Django 5.2.1 on 2025-05-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='sipnosis',
            field=models.TextField(null=True, verbose_name='Sipnosis'),
        ),
    ]
