# Generated by Django 5.2.1 on 2025-05-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_alter_pelicula_sipnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='opinion',
            field=models.TextField(blank=True, null=True, verbose_name='Opinion'),
        ),
    ]
